name: Run Zefoy CAPTCHA Solver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-captcha-solver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser tesseract-ocr libtesseract-dev
          [ -f /usr/bin/chromedriver ] || sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytesseract pillow

      - name: Run CAPTCHA Solver
        run: |
          python your_script_name.py
